package frames_test

// video_test.go — Phase 7.47 hero-video frame emitter.
//
// Sibling of frames_test.go (the static README frames). This file owns the
// VIDEO storyboard: a sequence of .ansi frames that, played back in order with
// timing (assets/video/hero.tape), animates the master-fable-rebuild ramp —
// cost dripping, cache_read climbing, the ⏱ TTL ageing, and finally the 240K
// cache rebuild flashing red on the freshest turn.
//
// Same honesty principle as the static frames: states are synthetic (the fixture
// is truncated to a growing turn count and observed at a moving `now`), but the
// render is the REAL production pipeline (assembler → renderer.Apply). Each frame
// is internally honest — per-turn $ is each turn's real token price (Phase 7.46
// table-driven cost), the session total is the sum of the visible turns.
//
// Gated behind CC_PROBELINE_VIDEO_DIR (separate from the static emitter's
// CC_PROBELINE_EMIT_DIR) so `go test ./...` stays hermetic and asset-free:
//
//	CC_PROBELINE_VIDEO_DIR=<dir> go test ./tests/frames/ -run EmitVideoFrames -v
//
// Driver: scripts/build-video-frames.sh emits into assets/video/frames/.

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/labzink/cc-probeline/internal/cost"
	"github.com/labzink/cc-probeline/internal/mode"
	"github.com/labzink/cc-probeline/internal/parser"
	"github.com/labzink/cc-probeline/internal/probes"
	"github.com/labzink/cc-probeline/internal/renderer"
	"github.com/labzink/cc-probeline/internal/state"
	"github.com/labzink/cc-probeline/internal/statusline"
	"github.com/labzink/cc-probeline/internal/stdin"
	"github.com/labzink/cc-probeline/tests/testutil"
)

// Video fixtures (generated by scripts/_gen_video_fixtures.py). Opus 4.8.
const (
	fxVideoAct1    = "tests/frames/testdata/video-act1/master.jsonl"
	fxVideoAct1Sub = "tests/frames/testdata/video-act1/sidecar"
	fxVideoAct2    = "tests/frames/testdata/video-act2/master.jsonl"
)

var opus48 = stdin.Model{ID: "claude-opus-4-8", Name: "Opus 4.8"}

// vframe is one storyboard beat. The fixture is truncated to its first keepTurns
// ASSISTANT turns (so the newest visible turn is #keepTurns), observed at moment
// `now`. A fixed 10-row window (videoData sets TableRows=10) makes turns appear
// one at a time. Quota / context / extra-usage are set per-beat to drive the
// Act-2 escalation; hintStart rotates the bottom tip every few beats.
type vframe struct {
	name      string
	fixture   string // default fxVideoAct1
	subDir    string // sidecar dir → collect a subagent ↳ row (Act 1)
	keepTurns int    // newest visible assistant turn number
	now       time.Time

	ctxSize int // context-window size; 0 → 1_000_000
	ctxUsed int // 0 → newest turn's cache_read

	pct5h, pct7d     float64
	reset5h, reset7d time.Duration
	extraActive      bool
	extraUSD         float64
	rebuilt          bool // emit the "⚠ Cache rebuilt" alert (overrides the hint)
	hintStart        int
}

// vt builds an observation moment on the fixture's day (2026-06-05 UTC).
func vt(h, m int) time.Time { return time.Date(2026, 6, 5, h, m, 0, 0, time.UTC) }

// videoFrames is the full hero storyboard — one continuous loop, two acts.
//
// ACT 1 — "anatomy of a session" (video-act1, Opus 4.8): the cache_read ramp
// 8K→240K appears one turn at a time (#13→#17), a subagent ↳ row surfaces
// mid-ramp with its own Σ cost, the cache-TTL ⏱ ages 60m→0m while work pauses,
// then the freshest turn rebuilds the whole 240K cache (red write, cost spike).
//
// ACT 2 — "hitting the wall" (video-act2, Opus 4.8): much later in the same
// session, heavy turns #84→#92 pile up, context climbs past 500K (ctx bar reddens
// the first time), the 5h limit fills into the red and reaches 100%, and
// extra-usage kicks in (+$ overage). The bottom hint rotates throughout.
//
// _make_cast.py inserts a dim "later…" interstitial between the two acts.
func videoFrames() []vframe {
	const day4 = 4 * 24 * time.Hour
	return []vframe{
		// ── ACT 1 — one turn at a time (orch → subagent → orch …) ────────────
		{name: "s_a0", keepTurns: 13, now: vt(10, 31), pct5h: 26, pct7d: 70, reset5h: 4 * time.Hour, reset7d: day4, hintStart: 0},
		{name: "s_a1", keepTurns: 14, now: vt(10, 33), pct5h: 28, pct7d: 70, reset5h: 4 * time.Hour, reset7d: day4, hintStart: 0},
		{name: "s_a2", keepTurns: 14, now: vt(10, 35), subDir: fxVideoAct1Sub, pct5h: 30, pct7d: 71, reset5h: 4 * time.Hour, reset7d: day4, hintStart: 0},               // SUBAGENT row surfaces
		{name: "s_a3", keepTurns: 15, now: vt(10, 37), subDir: fxVideoAct1Sub, pct5h: 31, pct7d: 71, reset5h: 4 * time.Hour, reset7d: day4, hintStart: 1},               // orch #15 returns
		{name: "s_a4", keepTurns: 16, now: vt(10, 39), subDir: fxVideoAct1Sub, pct5h: 32, pct7d: 72, reset5h: 4 * time.Hour, reset7d: day4, hintStart: 1},               // orch #16
		{name: "s_a5", keepTurns: 17, now: vt(10, 42), subDir: fxVideoAct1Sub, pct5h: 34, pct7d: 72, reset5h: 3 * time.Hour, reset7d: day4, hintStart: 1},               // orch #17 — cache 240K peak
		{name: "s_a6", keepTurns: 17, now: vt(11, 20), subDir: fxVideoAct1Sub, pct5h: 34, pct7d: 72, reset5h: 3 * time.Hour, reset7d: day4, hintStart: 2},               // TTL aged ~20m (no new turn)
		{name: "s_a7", keepTurns: 17, now: vt(11, 45), subDir: fxVideoAct1Sub, pct5h: 35, pct7d: 73, reset5h: 2 * time.Hour, reset7d: day4, hintStart: 2},               // TTL 0m — held longer
		{name: "s_a8", keepTurns: 18, now: vt(12, 0), subDir: fxVideoAct1Sub, rebuilt: true, pct5h: 36, pct7d: 73, reset5h: 2 * time.Hour, reset7d: day4, hintStart: 2}, // REBUILD flash — HOLD

		// ── ACT 2 — one turn at a time, escalation (after the interstitial).
		// Context window is the full 1M, so used 493K→530K crosses the 50% line
		// (green→yellow) around 500K — a calm warning, not red. No row highlight
		// in Act 2 (only Act 1 highlights the new row).
		{name: "s_b0", fixture: fxVideoAct2, keepTurns: 84, now: vt(15, 30), pct5h: 82, pct7d: 84, reset5h: 90 * time.Minute, reset7d: 3 * 24 * time.Hour, hintStart: 3},
		{name: "s_b1", fixture: fxVideoAct2, keepTurns: 85, now: vt(15, 36), pct5h: 85, pct7d: 85, reset5h: 84 * time.Minute, reset7d: 3 * 24 * time.Hour, hintStart: 5}, // config tip — plated on this calm beat
		{name: "s_b2", fixture: fxVideoAct2, keepTurns: 86, now: vt(15, 42), pct5h: 88, pct7d: 86, reset5h: 78 * time.Minute, reset7d: 3 * 24 * time.Hour, hintStart: 3}, // ctx crosses 500K → yellow
		{name: "s_b3", fixture: fxVideoAct2, keepTurns: 87, now: vt(15, 48), pct5h: 91, pct7d: 88, reset5h: 72 * time.Minute, reset7d: 3 * 24 * time.Hour, hintStart: 4},
		{name: "s_b4", fixture: fxVideoAct2, keepTurns: 88, now: vt(15, 54), pct5h: 94, pct7d: 90, reset5h: 66 * time.Minute, reset7d: 3 * 24 * time.Hour, hintStart: 4},
		{name: "s_b8", fixture: fxVideoAct2, keepTurns: 92, now: vt(16, 12), pct5h: 100, pct7d: 95, reset5h: 48 * time.Minute, reset7d: 3 * 24 * time.Hour, extraActive: true, extraUSD: 2.40, hintStart: 5}, // 5h 100% + extra-usage — HOLD
	}
}

func TestEmitVideoFrames(t *testing.T) {
	dir := os.Getenv("CC_PROBELINE_VIDEO_DIR")
	if dir == "" {
		t.Skip("set CC_PROBELINE_VIDEO_DIR to emit hero-video .ansi frames")
	}
	if !filepath.IsAbs(dir) {
		dir = filepath.Join(testutil.ProjectRoot(t), dir)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", dir, err)
	}

	th := realTheme()
	for _, vf := range videoFrames() {
		vf := vf
		t.Run(vf.name, func(t *testing.T) {
			d, cfg := videoData(t, vf)
			a := statusline.Assembler{Mode: mode.Standard, Theme: th, Cols: 130, Config: cfg}
			out := renderer.Apply(a.Render(d), th)
			path := filepath.Join(dir, vf.name+".ansi")
			if err := os.WriteFile(path, []byte(out), 0o644); err != nil {
				t.Fatalf("write %s: %v", path, err)
			}
			t.Logf("wrote %s (%d bytes)", path, len(out))
		})
	}
}

// videoData mirrors scenarioData (frames_test.go) but is data-driven by the
// vframe: per-beat fixture, subagent sidecar, observation moment, context window,
// quota and extra-usage. Opus 4.8, clean git, fixed 10-row window.
func videoData(t *testing.T, vf vframe) (probes.Data, probes.Config) {
	t.Helper()
	root := testutil.ProjectRoot(t)
	t.Setenv("CC_PROBELINE_QUOTA_DIR", t.TempDir())

	fixture := vf.fixture
	if fixture == "" {
		fixture = fxVideoAct1
	}
	records := parseTruncated(t, filepath.Join(root, fixture), vf.keepTurns)
	session := parser.Aggregate(parser.Dedup(records))

	var subagents []parser.SubagentStats
	if vf.subDir != "" {
		subs, err := parser.CollectSubagents(context.Background(), filepath.Join(root, vf.subDir))
		if err != nil {
			t.Fatalf("CollectSubagents: %v", err)
		}
		subagents = subs
	}

	st := &state.Session{}
	allTurns := make([]parser.Turn, len(session.Turns))
	copy(allTurns, session.Turns)
	for i := range subagents {
		allTurns = append(allTurns, subagents[i].Turns...)
	}
	durMS := vf.now.Sub(vt(8, 0)).Milliseconds()
	cost.Reconcile(st, 0, 0, nil)
	cost.Reconcile(st, 0, durMS, allTurns)
	// The header reads the official meter (d.Stdin.Cost.TotalCostUSD), not our
	// estimate (Phase 7.46, probes/cost.go). For the synthetic video we feed the
	// estimate Σ in as that "official" total so the header tracks the visible
	// turns instead of reading $0.00 from an absent live meter.
	sessTotal := cost.SessionTotal(st, 0)

	ctxSize := vf.ctxSize
	if ctxSize == 0 {
		ctxSize = 1_000_000
	}
	ctxUsed := vf.ctxUsed
	if ctxUsed == 0 {
		if n := len(session.Turns); n > 0 {
			ctxUsed = session.Turns[n-1].Tokens.CacheRead
		}
		if ctxUsed == 0 {
			ctxUsed = 60_000
		}
	}

	payload := stdin.Payload{
		Model:         opus48,
		SessionID:     "video-" + vf.name,
		Cwd:           "/Users/dev/Projects/cc-probeline",
		ContextWindow: ctxWindow(ctxSize, ctxUsed),
		Cost:          stdin.Cost{TotalCostUSD: sessTotal, TotalAPIDurationMS: durMS},
		RateLimits:    vrl(vf),
	}

	var events []parser.CacheEvent
	if vf.rebuilt {
		events = []parser.CacheEvent{{Type: parser.OrchTTL, Timestamp: vf.now}}
	}

	d := probes.Data{
		Stdin:            payload,
		Session:          &session,
		Subagents:        subagents,
		Git:              &parser.GitStatus{Branch: "main", ModifiedCount: 0},
		Now:              vf.now,
		SessionID:        payload.SessionID,
		State:            st,
		ExtraCacheEvents: events,
		ExtraActive:      vf.extraActive,
		ExtraUSD:         vf.extraUSD,
		HintStart:        vf.hintStart,
	}
	d.SessionTotal = sessTotal
	d.SessionDurMS = cost.SessionDuration(st, durMS)
	curGroupID := 0
	if len(session.Turns) > 0 {
		curGroupID = session.Turns[len(session.Turns)-1].GroupID
	}
	d.LastRequestCost = cost.LastRequest(st, 0, curGroupID)
	captured := st
	d.PerTurnCostFn = func(uuid string) (float64, bool) { return cost.PerTurn(captured, uuid) }

	cfg := richProbesCfg()
	cfg.TableRows = 10 // fixed sliding window — turns appear one at a time
	return d, cfg
}

// vrl builds the per-beat RateLimits, anchoring the reset countdown to the frame's
// own `now` so the "↻ time-to-reset" reads sensibly across the moving timeline.
func vrl(vf vframe) *stdin.RateLimits {
	return &stdin.RateLimits{
		FiveHour: stdin.RateWindow{UsedPercentage: vf.pct5h, ResetsAt: jsonTime(vf.now.Add(vf.reset5h))},
		SevenDay: stdin.RateWindow{UsedPercentage: vf.pct7d, ResetsAt: jsonTime(vf.now.Add(vf.reset7d))},
	}
}

// parseTruncated reads the fixture and keeps records up to and including the
// keepTurns-th ASSISTANT record (plus any user records before it), synthesising
// an earlier point in the session where the newest turn is #keepTurns.
func parseTruncated(t *testing.T, path string, keepTurns int) []parser.Record {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var kept []string
	assistants := 0
	for _, line := range strings.Split(string(raw), "\n") {
		if strings.TrimSpace(line) == "" {
			continue
		}
		kept = append(kept, line)
		if strings.Contains(line, `"type": "assistant"`) || strings.Contains(line, `"type":"assistant"`) {
			assistants++
			if assistants >= keepTurns {
				break
			}
		}
	}
	records, _, scanErr := parser.ParseLines(strings.NewReader(strings.Join(kept, "\n") + "\n"))
	if scanErr != nil {
		t.Fatalf("ParseLines truncated %s: %v", path, scanErr)
	}
	return records
}
