package probes

import (
	"fmt"
	"log/slog"
	"time"

	"github.com/labzink/cc-probeline/internal/quota"
	"github.com/labzink/cc-probeline/internal/renderer"
	"github.com/labzink/cc-probeline/internal/stdin"
)

// Window lengths used to decide whether a persisted snapshot's used-percentage
// has rolled over. A snapshot is a point-in-time observation valid only until
// its window resets; past that moment the stored percentage is meaningless.
const (
	fiveHourWindow = 5 * time.Hour
	sevenDayWindow = 7 * 24 * time.Hour
)

// usageMaxAge gates everything sourced from the ~/.claude.json usage cache (the
// model-scoped window and the overage badge). That cache is refreshed only by
// Claude Code's /usage screen — which we trigger ourselves, but which can fail
// silently — so past this age we drop those blocks instead of showing numbers
// nobody can trust. The weekly percentage only ever climbs, so a stale reading
// understates rather than overstates; the age is still shown as a dim "⏱ 2m".
const usageMaxAge = time.Hour

// resetMatchSlack is how far apart two reset instants may be and still count as
// the same moment. The weekly windows are generated by one API response, so the
// timestamps differ only by microseconds of generation time — but if a model
// window ever resets on its own schedule, each block keeps its own countdown
// rather than letting one timer speak for both.
const resetMatchSlack = time.Minute

// windowExpired reports whether a rate-limit window has rolled over since the
// snapshot was taken, in which case its stored used-percentage must read 0
// rather than the stale high value. Two independent signals:
//
//  1. reset known and in the past (reset>0 && now>=reset) — the window has
//     definitely reset.
//  2. reset unknown (reset==0, CC sent null) but the snapshot is older than the
//     window length — it must have rolled over at least once.
//
// A window whose reset is still in the future keeps its stored percentage.
func windowExpired(reset int64, snapTS time.Time, now time.Time, windowLen time.Duration) bool {
	if reset > 0 {
		return now.Unix() >= reset
	}
	return now.Sub(snapTS) > windowLen
}

// displayPctInt converts a used-percentage to the integer shown in the status
// line. By default it truncates (matching every other percentage display). When
// roundUp is true it rounds half-up, so the number flips to 100 at 99.5 instead
// of parking on 99 until a literal 100.0.
//
// Phase 7.45 B5: applied to the 5-hour window only. The 5h window is the one
// that throttles soonest, so a small nudge toward "100" right before the wall is
// worth the slight asymmetry; the 7-day window keeps truncation (its scale is
// long enough that an early 100 would mislead, not warn). Display-only: it never
// feeds the overage trigger or colour thresholds, which stay on the raw float —
// so the paid-overage badge cannot fire early off a rounded number.
func displayPctInt(pct float64, roundUp bool) int {
	if roundUp {
		return int(pct + 0.5) // pct is always ≥ 0, so +0.5+truncate == round-half-up
	}
	return int(pct)
}

// quotaUsageColor returns the raw ANSI colour code for a quota usage percentage
// using the window's configurable notice/warn/critical ratios: green below
// notice, yellow at notice, orange at warn, red at critical. It mirrors
// renderer.ProgressBarColor but with per-window thresholds; like that function it
// caps at Red — the >95% bold-red emphasis is applied separately by boldRedWrap.
// Returns "" when ANSI is disabled.
func quotaUsageColor(pct, notice, warn, critical float64, t renderer.Theme) string {
	if !t.AnsiEnabled {
		return ""
	}
	switch {
	case pct >= critical*100.0:
		return t.Colors.Red
	case pct >= warn*100.0:
		return t.Colors.Orange
	case pct >= notice*100.0:
		return t.Colors.Yellow
	default:
		return t.Colors.Green
	}
}

// QuotaProbe renders quota usage for the 5-hour and 7-day rate-limit windows.
// Data is sourced from quota.Freshest() (cross-session persistent file) with
// d.Stdin.RateLimits as a fallback when no snapshot has been stored yet.
//
// Visible only when Config.QuotaEnabled=true AND either quota.Freshest() returns
// a snapshot OR d.Stdin.RateLimits != nil.
type QuotaProbe struct{}

func (p *QuotaProbe) Name() string  { return "quota" }
func (p *QuotaProbe) Priority() int { return 1 }
func (p *QuotaProbe) MinWidth() int { return len("0% · 0%") }

// Visible returns true only when QuotaEnabled is true and quota data is available
// (either from the persistent Freshest snapshot or from the current payload).
func (p *QuotaProbe) Visible(d Data, c Config) bool {
	if !c.QuotaEnabled {
		return false
	}
	_, hasFresh := quota.Freshest()
	return hasFresh || d.Stdin.RateLimits != nil
}

// Render formats the quota blocks.
//
// Data source priority:
//  1. quota.Freshest() — cross-session persistent snapshot (account-wide freshest).
//  2. d.Stdin.RateLimits — current payload fallback when no snapshot exists.
//
// Colour markers applied per B3 §5:
//   - progress bars wrapped in ProgressBarColor(pct, th) + bar + Reset
//   - ↻ reset countdown wrapped in {{color:yellow}} when time-to-reset < 30m
//   - percentage value wrapped in {{color:bold_red}} when pct > 95
//
// Display levels:
//
//	Full:    "5h: <bar10_5h> <reset5h> · 7d: <bar10_7d> <reset7d>"
//	Compact: "<bar5_5h> <reset5h> · <bar5_7d> <reset7d>"
//	Minimal: "<pct5h>% · <pct7d>%"
func (p *QuotaProbe) Render(d Data, c Config, t renderer.Theme, level Level) string {
	// Resolve data source: freshest-wins cross-session snapshot takes priority.
	snap, hasFresh := quota.Freshest()

	var pct5h, pct7d float64
	var rl *stdin.RateLimits

	if hasFresh {
		pct5h = snap.FiveHourPct
		pct7d = snap.SevenDayPct
		// snapTime is the observation time (used below for window rollover).
		snapTime := time.UnixMilli(snap.TS)
		// A window that has rolled over since the snapshot was taken reads 0%:
		// the stored high percentage belongs to a window that has already reset.
		// This clears the stale-90% mirage seen after a laptop sleeps overnight
		// or right after /clear, before CC sends a fresh rate_limits payload.
		if windowExpired(snap.FiveHourReset, snapTime, d.Now, fiveHourWindow) {
			pct5h = 0
		}
		if windowExpired(snap.SevenDayReset, snapTime, d.Now, sevenDayWindow) {
			pct7d = 0
		}
		// Use current payload rate_limits for reset-countdown times (they are
		// session-local and not stored in the snapshot).
		rl = d.Stdin.RateLimits
	} else if d.Stdin.RateLimits != nil {
		// Fallback to current payload when no persistent snapshot exists.
		rl = d.Stdin.RateLimits
		pct5h = rl.FiveHour.UsedPercentage
		pct7d = rl.SevenDay.UsedPercentage
	} else {
		slog.Warn("quota.Render: called with no snapshot and nil RateLimits; returning empty")
		return ""
	}

	// colourReset returns the reset escape only when AnsiEnabled.
	colourReset := ""
	if t.AnsiEnabled {
		colourReset = t.Colors.Reset
	}

	// Per-window colour-flip ratios (notice/warn/critical), resolved with the
	// baked defaults 0.50/0.70/0.90 when unset or invalid.
	n5, w5, c5 := resolveRatios(c.Quota5hNoticeRatio, c.Quota5hWarnRatio, c.Quota5hCriticalRatio)
	n7, w7, c7 := resolveRatios(c.Quota7dNoticeRatio, c.Quota7dWarnRatio, c.Quota7dCriticalRatio)

	// boldRedWrap wraps a value string with {{color:bold_red}}...{{reset}} when
	// the percentage exceeds 95 and ANSI output is enabled. Markers are gated
	// on AnsiEnabled so that plain-text callers never receive raw markers.
	boldRedWrap := func(pct float64, s string) string {
		if t.AnsiEnabled && pct > 95.0 {
			return "{{color:bold_red}}" + s + "{{reset}}"
		}
		return s
	}

	// Reset countdown resolution: live stdin resets_at first, then the persisted
	// snapshot's reset unix (cross-session — lets an idle session show the countdown
	// once an active session has observed the new window), then "↻ ??m" when neither
	// is known (window just reset, next one not ticking yet).
	var live5h, live7d []byte
	if rl != nil {
		live5h = rl.FiveHour.ResetsAt
		live7d = rl.SevenDay.ResetsAt
	}
	var snap5hReset, snap7dReset int64
	if hasFresh {
		snap5hReset = snap.FiveHourReset
		snap7dReset = snap.SevenDayReset
	}
	reset5h := formatReset(live5h, snap5hReset, d.Now, fiveHourThresholds)
	reset7d := formatReset(live7d, snap7dReset, d.Now, sevenDayThresholds)

	// pctSuffix returns " NN%" for Full/Compact. The number appears once the
	// window reaches its critical ratio (and is below 100%); colour is red, or
	// bold_red above 95% (boldRedWrap also reddens the whole block there). Below
	// critical the number is omitted — the bar carries the signal. Phase 6.95.h:
	// at pct ≥ 100 the number is dropped and the extra-usage block stands in.
	pctSuffix := func(pct, critical float64, roundUp bool) string {
		if pct < critical*100.0 || pct >= 100.0 {
			return ""
		}
		pctStr := fmt.Sprintf("%d%%", displayPctInt(pct, roundUp))
		if !t.AnsiEnabled {
			// AnsiEnabled=false: emit plain suffix without colour markers.
			return " " + pctStr
		}
		if pct > 95.0 {
			return " {{color:bold_red}}" + pctStr + "{{reset}}"
		}
		return " {{color:red}}" + pctStr + "{{reset}}"
	}

	// Phase 7.48: the model-scoped weekly window (e.g. "fable"). It rides inside
	// the 7-day block in brackets, because it is a slice of that same week rather
	// than a third independent window — hence brackets and not the " · " that
	// separates peers. Gated on cache freshness: a stale snapshot shows nothing.
	usageFresh := d.UsageAge <= usageMaxAge
	model := d.ModelWindow
	if !usageFresh {
		model = nil
	}

	// Reset countdown for the model window, and whether it coincides with the
	// 7-day one. When they coincide (the normal case — one API response stamps
	// both) a single countdown after the bracket speaks for the whole weekly
	// group; otherwise each block keeps its own.
	sharedWeeklyReset := false
	resetModel := ""
	if model != nil {
		reset7dTime, known7d := resolveReset(live7d, snap7dReset)
		if known7d && model.ResetUnix > 0 {
			diff := time.Unix(model.ResetUnix, 0).Sub(reset7dTime)
			if diff < 0 {
				diff = -diff
			}
			sharedWeeklyReset = diff <= resetMatchSlack
		}
		if !sharedWeeklyReset {
			resetModel = formatReset(nil, model.ResetUnix, d.Now, sevenDayThresholds)
		}
	}

	// minimalPctColour wraps "NN%" in the window's usage colour using the
	// configurable notice/warn/critical ratios (green below notice · yellow ·
	// orange · red at critical); pct > 95 overrides to bold_red (same rule
	// boldRedWrap applies in Full/Compact). Markers are gated on AnsiEnabled so
	// plain callers receive an uncoloured "NN%".
	minimalPctColour := func(pct, notice, warn, critical float64, roundUp bool) string {
		pctStr := fmt.Sprintf("%d%%", displayPctInt(pct, roundUp))
		if !t.AnsiEnabled {
			return pctStr
		}
		var marker string
		switch {
		case pct > 95.0:
			marker = "{{color:bold_red}}"
		case pct >= critical*100.0:
			marker = "{{color:red}}"
		case pct >= warn*100.0:
			marker = "{{color:orange}}"
		case pct >= notice*100.0:
			marker = "{{color:yellow}}"
		default:
			marker = "{{color:green}}"
		}
		return marker + pctStr + "{{reset}}"
	}

	// overageBadge renders the paid-overage badge: Anthropic's own figure for how
	// much extra usage was spent this billing month against its ceiling, plus a
	// dim age marker because the figure comes from a cache refreshed at most
	// every 5 minutes. It sits after the whole quota group rather than beside one
	// window: the figure is account-wide and belongs to no single window.
	// Empty when overage is off, unknown, or the snapshot is stale.
	overageBadge := func(lvl Level) string {
		o := d.Overage
		if !usageFresh || o == nil || !o.Enabled || o.LimitUSD <= 0 {
			return ""
		}
		// Degrade like every other block: the monthly ceiling is context, the
		// spent figure is the signal. Keeping "/ $120.00" in Compact costs ten
		// columns and, at 80 columns, pushes the whole quota block down a level —
		// trading the bars for a number nobody is waiting for.
		var amt string
		switch lvl {
		case LevelFull:
			amt = fmt.Sprintf("+$%.2f / $%.2f extra usage", o.UsedUSD, o.LimitUSD)
		case LevelCompact:
			amt = fmt.Sprintf("+$%.2f extra", o.UsedUSD)
		default: // LevelMinimal
			amt = fmt.Sprintf("+$%.2f", o.UsedUSD)
		}
		age := "⏱ " + formatUsageAge(d.UsageAge)
		if !t.AnsiEnabled {
			return " " + amt + " " + age
		}
		return " {{color:red}}" + amt + "{{reset}} {{dim}}" + age + "{{reset}}"
	}

	// modelLabels returns the bracket label for the model window at this level:
	// the full name in Full ("fable: "), its initial in the tighter levels
	// ("f: "). Some label is mandatory — Compact and Minimal carry no "5h:"/"7d:"
	// prefixes at all, so an unlabelled third value would be readable only by
	// position.
	modelLabel := func(lvl Level) string {
		if model == nil {
			return ""
		}
		if lvl == LevelFull {
			return model.Name + ": "
		}
		return string([]rune(model.Name)[:1]) + ": "
	}

	// weeklyGroup assembles the 7-day block and, when a model window exists, that
	// window in brackets right after it. With both weekly resets coinciding (the
	// normal case) one countdown follows the bracket and speaks for the group;
	// otherwise each block carries its own.
	weeklyGroup := func(prefix, bar7d, barModel string, lvl Level) string {
		val7d := fmt.Sprintf("%s%s", bar7d, pctSuffix(pct7d, c7, false))
		if model == nil {
			return prefix + boldRedWrap(pct7d, val7d+" "+reset7d)
		}
		inner := boldRedWrap(model.Pct, modelLabel(lvl)+barModel+pctSuffix(model.Pct, c7, false))
		if sharedWeeklyReset {
			return prefix + boldRedWrap(pct7d, val7d) + " (" + inner + ") " + reset7d
		}
		return prefix + boldRedWrap(pct7d, val7d+" "+reset7d) + " (" + inner + " " + resetModel + ")"
	}

	switch level {
	case LevelFull:
		bar5h := quotaUsageColor(pct5h, n5, w5, c5, t) +
			renderer.ProgressBar10(pct5h) + colourReset
		bar7d := quotaUsageColor(pct7d, n7, w7, c7, t) +
			renderer.ProgressBar10(pct7d) + colourReset
		barModel := ""
		if model != nil {
			barModel = quotaUsageColor(model.Pct, n7, w7, c7, t) +
				renderer.ProgressBar10(model.Pct) + colourReset
		}
		val5h := boldRedWrap(pct5h, fmt.Sprintf("%s%s %s", bar5h, pctSuffix(pct5h, c5, true), reset5h))
		return fmt.Sprintf("5h: %s · %s", val5h, weeklyGroup("7d: ", bar7d, barModel, LevelFull)) +
			overageBadge(LevelFull)
	case LevelCompact:
		bar5h := quotaUsageColor(pct5h, n5, w5, c5, t) +
			renderer.ProgressBar(pct5h) + colourReset
		bar7d := quotaUsageColor(pct7d, n7, w7, c7, t) +
			renderer.ProgressBar(pct7d) + colourReset
		barModel := ""
		if model != nil {
			barModel = quotaUsageColor(model.Pct, n7, w7, c7, t) +
				renderer.ProgressBar(model.Pct) + colourReset
		}
		val5h := boldRedWrap(pct5h, fmt.Sprintf("%s%s %s", bar5h, pctSuffix(pct5h, c5, true), reset5h))
		return fmt.Sprintf("%s · %s", val5h, weeklyGroup("", bar7d, barModel, LevelCompact)) +
			overageBadge(LevelCompact)
	default: // LevelMinimal
		// Minimal drops the bar; the number stands in its place, coloured by the
		// same rules the bar would use, and the reset countdown is kept like
		// Compact (6.95.e). The number stays even at ≥100% — it is the only quota
		// signal at this level (6.95.h hides it only when a bar is present).
		val5h := minimalPctColour(pct5h, n5, w5, c5, true) + " " + reset5h
		val7d := minimalPctColour(pct7d, n7, w7, c7, false)
		if model == nil {
			return fmt.Sprintf("%s · %s %s", val5h, val7d, reset7d) + overageBadge(LevelMinimal)
		}
		inner := modelLabel(LevelMinimal) + minimalPctColour(model.Pct, n7, w7, c7, false)
		if sharedWeeklyReset {
			return fmt.Sprintf("%s · %s (%s) %s", val5h, val7d, inner, reset7d) +
				overageBadge(LevelMinimal)
		}
		return fmt.Sprintf("%s · %s %s (%s %s)", val5h, val7d, reset7d, inner, resetModel) +
			overageBadge(LevelMinimal)
	}
}

// resetThresholds defines the gradient colour thresholds for a reset countdown.
// Durations are checked in order; the first matching threshold wins.
// When no threshold matches (remaining > all limits) no marker is applied.
type resetThresholds struct {
	red    time.Duration // ≤ this → red
	orange time.Duration // ≤ this → orange
	green  time.Duration // ≤ this → green
	// > green → no marker
}

// fiveHourThresholds holds the 5-hour reset colour thresholds (spec §2.3):
//
//	≤ 10m → red
//	≤ 30m → orange
//	≤ 60m → green
//	> 60m → no marker
var fiveHourThresholds = resetThresholds{
	red:    10 * time.Minute,
	orange: 30 * time.Minute,
	green:  60 * time.Minute,
}

// sevenDayThresholds holds the 7-day reset colour thresholds (spec §2.3):
//
//	≤ 5h  → red
//	≤ 24h → orange
//	≤ 2d  → green
//	> 2d  → no marker
var sevenDayThresholds = resetThresholds{
	red:    5 * time.Hour,
	orange: 24 * time.Hour,
	green:  48 * time.Hour,
}

// resetColourMarker returns the {{color:X}} marker for the given remaining duration
// using the supplied threshold table. Returns "" when no marker applies.
// Markers are always returned as text tokens; Apply converts them to ANSI.
func resetColourMarker(remaining time.Duration, th resetThresholds) string {
	switch {
	case remaining <= th.red:
		return "{{color:red}}"
	case remaining <= th.orange:
		return "{{color:orange}}"
	case remaining <= th.green:
		return "{{color:green}}"
	default:
		return ""
	}
}

// formatReset resolves a reset countdown from the freshest known source and
// applies a gradient colour marker based on the remaining time. Resolution order:
//
//  1. live stdin resets_at (liveRaw) — session-local, most precise;
//  2. persisted snapshot reset unix (snapUnix > 0) — cross-session fallback so an
//     idle session can still show the countdown an active session has observed;
//  3. neither known → "↻ ??m" plain (no colour): the window just reset and the
//     next one has not started ticking, so the time is genuinely unknown.
//
// A parseable-but-past reset (dur <= 0) renders "↻ 0m" — distinct from the
// unknown "↻ ??m" case. Colour markers are emitted as {{color:X}}…{{reset}} text
// tokens; Apply()/renderer strip them when colour is off.
func formatReset(liveRaw []byte, snapUnix int64, now time.Time, thresholds resetThresholds) string {
	resetTime, known := resolveReset(liveRaw, snapUnix)
	if !known {
		slog.Debug("quota.formatReset: reset time unknown (live + snapshot both absent); rendering ??m")
		return "↻ ??m"
	}
	dur := resetTime.Sub(now)
	if dur <= 0 {
		return "↻ 0m"
	}
	text := formatDuration(dur)
	marker := resetColourMarker(dur, thresholds)
	if marker == "" {
		return text
	}
	return marker + text + "{{reset}}"
}

// resolveReset resolves a reset time from the freshest known source: live stdin
// resets_at first, then the persisted snapshot reset unix. Returns (time, true)
// when known, (zero, false) when neither source is available. Shared by
// formatReset (countdown rendering) and the Phase 6.95.h extra-usage block
// placement (which window resets later carries the badge).
func resolveReset(liveRaw []byte, snapUnix int64) (time.Time, bool) {
	if t, ok := stdin.ParseResetsAt(liveRaw); ok {
		return t, true
	}
	if snapUnix > 0 {
		return time.Unix(snapUnix, 0), true
	}
	return time.Time{}, false
}

// laterReset reports whether window A's reset is later than window B's, used to
// decide which window carries the extra-usage badge when both are at 100%
// (draft §5: attach to the window that resets later — it holds the overage
// longest). A known reset always beats an unknown one; when both are unknown the
// caller's A (the 7-day window) wins as the longer-lived default.
func laterReset(a time.Time, aKnown bool, b time.Time, bKnown bool) bool {
	switch {
	case aKnown && bKnown:
		return a.After(b)
	case aKnown:
		return true
	case bKnown:
		return false
	default:
		return true
	}
}

// formatDuration renders a duration as "↻ <d>d.<h>h" when ≥24h,
// else "↻ <h>h:<m>m". Space after ↻, colon between h/m, dot between d/h.
// formatUsageAge renders how old the usage-cache snapshot is, compactly: "0m",
// "7m", "1h". It is only ever called below usageMaxAge, so the hour form is a
// boundary case rather than the norm.
func formatUsageAge(age time.Duration) string {
	if age < 0 {
		age = 0
	}
	if age >= time.Hour {
		return fmt.Sprintf("%dh", int(age.Hours()))
	}
	return fmt.Sprintf("%dm", int(age.Minutes()))
}

func formatDuration(dur time.Duration) string {
	totalMin := int(dur.Minutes())
	totalHours := totalMin / 60
	mins := totalMin % 60

	if totalHours >= 24 {
		days := totalHours / 24
		hours := totalHours % 24
		return fmt.Sprintf("↻ %dd.%dh", days, hours)
	}
	return fmt.Sprintf("↻ %dh:%dm", totalHours, mins)
}
